### PR TITLE
Use service name in nav

### PR DESCRIPTION
**Pull request by frankieroberto**
This lets the the X-GOVUK logo link to https://x-govuk.github.io and also means the site can be called 'GOV.UK Services List' (as it's a list of services on GOV.UK). 

Possibly this is confusing though? 😄 And I'm still not convinced that the service name looks clickable, but 🤷.

### Before

Screenshot 2024-09-02 at 22 03 16

### After

Screenshot 2024-09-02 at 22 02 57

### CODE REVIEW

**Comment by frankieroberto** [comment]
Thoughts @paulrobertlloyd @peteryates @vickytnz @stevenjmesser?

**Review by peteryates — APPROVED** [review]
Looks good. Agree there's a possibility of confusion but it's minimal.

**Comment by paulrobertlloyd** [comment]
A couple of worms escaping this can:

- How does this relate to other X-GOVUK projects (do they move the name down into the ‘service’ area)
- How does this relate to the website; I kinda want 2 links in the header (By topic, By organisation), but that would essentially reintroduce 2 homepage links (unless you changed the homepage, string is further pulled)
- What links _should_ be in the navigation (there are quite a few useful ones in the footer)

**Comment by paulrobertlloyd** [comment]
That this resolves ‘X-GOVUK Thing’ vs ’X-GOVUK; GOV.UK Thing’ is quite a convincing argument for the change, though.

**Comment by paulrobertlloyd** [comment]
(Continuing to think out loud), on the other sites we could then pull the search input into the ‘service’ area, as the site searches are local, not global… though that’s not possible with the Eleventy Plugin, yet.

**Comment by stevenjmesser** [comment]
Ship it

**Comment by frankieroberto** [comment]
> * How does this relate to other X-GOVUK projects (do they move their names down into the ‘service’ area?)

Maybe?! Although https://x-govuk.github.io probably doesn’t need a service header, but the other projects might?

> * How does this relate to the website; I kinda want 2 links in the header (By topic, By organisation), but that would essentially reintroduce 2 homepage links (unless you changed the homepage, string is further pulled)

I’ve been wondering whether maybe there should be a separate homepage for https://govuk-digital-services.herokuapp.com which doesn't contain the list at all, but just introduces the project a bit and maybe contains the recent updates (current in the right hand nav). And then both 'By topic' and 'By organisation' could be separate links in the header? 🤔 

> * What links _should_ be in the navigation (there are quite a few useful ones in the footer)

I’ve kinda used the footer for semi-experimental bonus features 😄 but maybe some of them could be promoted? Which ones do you think are most useful?

**Comment by frankieroberto** [comment]
I'm gonna merge this for now, and will pick up some of the other points as separate PRs or issues.

If we think this ends up being a bad idea we can revert back.

**Pull request merged**
